name: prayerly
description: "Prayerly app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  geocoding: ^4.0.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

assets:
  - assets/icons/icon.png
flutter_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon.png"
  adaptive_icon_background: "#7cfc00"
# flutter pub run flutter_launcher_icons:main
